### ISSUE TITLE
Setting up bungeecord?

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#22]
OK so ive done this on 1.7 perfectly fine but for some reason its not working for 1.6

I am doing Bungee -> Minetick -> MCPC+ 1.6.4
I have the bungee setup correctly just as i had it setup on the 1.7 network. But the 1.6.4 MCPC+ server is not connecting to the forced host or the bungee network.

Is there something i need to configure in the spigot.yml other then bungeecord: true?

**Comment by Zilacon** [comment]
So i cant connect to the bungeecord or the hub server. The hub is set to port 7856 while the bungee server is set to 7800.

Going to mc.apocgaming.org:port for both is blocked but yet it is open on both the router and server.

Another server MCPC+ 1.6.4 is able to be connected to by doing mc.apocgaming.org:7852 just fine. But the forced host for it ashc.apocgaming.org does not work. Basically anything to do with Bungee is not working including Minetick.

Any idea whats going on?
Here is my Bungee config:

```
groups:
  Zilacon:
  - admin
  Sentinel618:
  - admin
disabled_commands:
- find
player_limit: -1
stats: b68ce147-0866-4f4f-8042-fda669cb4114
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- max_players: 1000
  fallback_server: HUB
  host: 0.0.0.0:7800
  bind_local_address: true
  ping_passthrough: false
  tab_list: GLOBAL_PING
  default_server: HUB
  forced_hosts:
    hub1.apocgaming.org: HUB
    ashc.apocgaming.org: ASHC
  tab_size: 60
  force_default_server: false
  motd: '&9A&fpocalyptic &9G&faming &9N&fetwork &b| &a26 Servers, One Network!'
  query_enabled: true
  query_port: 7800
timeout: 30000
connection_throttle: -1
servers:
  HUB:
    address: localhost:7856
    restricted: false
    motd: '&cAPOC TEST HUB 1.6.4'
  ASHC:
    address: localhost:7852
    restricted: false
    motd: '&9A&fpocalyptic &9G&faming &9N&fetwork &cAgrarian Skies 3.1.4'
ip_forward: true
online_mode: true
```
